name: CI
on:
  push:
    branches: ["**"]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - 'src/**'

      - name: Install dependencies
        if: steps.changes.outputs.src == 'true'
        run: npm install
      - name: Check types
        if: steps.changes.outputs.src == 'true'
        run: npm run typecheck
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - 'src/**'

      - name: Install dependencies
        if: steps.changes.outputs.src == 'true'
        run: npm install
      - name: Lint
        if: steps.changes.outputs.src == 'true'
        run: npm run lint
